package com.lxisoft.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryZoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryZoneAllPropertiesEquals(DeliveryZone expected, DeliveryZone actual) {
        assertDeliveryZoneAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryZoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryZoneAllUpdatablePropertiesEquals(DeliveryZone expected, DeliveryZone actual) {
        assertDeliveryZoneUpdatableFieldsEquals(expected, actual);
        assertDeliveryZoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryZoneAutoGeneratedPropertiesEquals(DeliveryZone expected, DeliveryZone actual) {
        assertThat(expected)
            .as("Verify DeliveryZone auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryZoneUpdatableFieldsEquals(DeliveryZone expected, DeliveryZone actual) {
        assertThat(expected)
            .as("Verify DeliveryZone relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getActive()).as("check active").isEqualTo(actual.getActive()))
            .satisfies(e -> assertThat(e.getBoundary()).as("check boundary").isEqualTo(actual.getBoundary()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryZoneUpdatableRelationshipsEquals(DeliveryZone expected, DeliveryZone actual) {
        // empty method
    }
}
