package com.lxisoft.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryRequestAllPropertiesEquals(DeliveryRequest expected, DeliveryRequest actual) {
        assertDeliveryRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryRequestAllUpdatablePropertiesEquals(DeliveryRequest expected, DeliveryRequest actual) {
        assertDeliveryRequestUpdatableFieldsEquals(expected, actual);
        assertDeliveryRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryRequestAutoGeneratedPropertiesEquals(DeliveryRequest expected, DeliveryRequest actual) {
        assertThat(expected)
            .as("Verify DeliveryRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryRequestUpdatableFieldsEquals(DeliveryRequest expected, DeliveryRequest actual) {
        assertThat(expected)
            .as("Verify DeliveryRequest relevant properties")
            .satisfies(e -> assertThat(e.getRequestDate()).as("check requestDate").isEqualTo(actual.getRequestDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryRequestUpdatableRelationshipsEquals(DeliveryRequest expected, DeliveryRequest actual) {
        assertThat(expected)
            .as("Verify DeliveryRequest relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()));
    }
}
