package com.lxisoft.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryPartnerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPartnerAllPropertiesEquals(DeliveryPartner expected, DeliveryPartner actual) {
        assertDeliveryPartnerAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryPartnerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPartnerAllUpdatablePropertiesEquals(DeliveryPartner expected, DeliveryPartner actual) {
        assertDeliveryPartnerUpdatableFieldsEquals(expected, actual);
        assertDeliveryPartnerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPartnerAutoGeneratedPropertiesEquals(DeliveryPartner expected, DeliveryPartner actual) {
        assertThat(expected)
            .as("Verify DeliveryPartner auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPartnerUpdatableFieldsEquals(DeliveryPartner expected, DeliveryPartner actual) {
        assertThat(expected)
            .as("Verify DeliveryPartner relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPartnerUpdatableRelationshipsEquals(DeliveryPartner expected, DeliveryPartner actual) {
        // empty method
    }
}
