package com.lxisoft.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FoodOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFoodOrderAllPropertiesEquals(FoodOrder expected, FoodOrder actual) {
        assertFoodOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertFoodOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFoodOrderAllUpdatablePropertiesEquals(FoodOrder expected, FoodOrder actual) {
        assertFoodOrderUpdatableFieldsEquals(expected, actual);
        assertFoodOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFoodOrderAutoGeneratedPropertiesEquals(FoodOrder expected, FoodOrder actual) {
        assertThat(expected)
            .as("Verify FoodOrder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFoodOrderUpdatableFieldsEquals(FoodOrder expected, FoodOrder actual) {
        assertThat(expected)
            .as("Verify FoodOrder relevant properties")
            .satisfies(e -> assertThat(e.getCustomerName()).as("check customerName").isEqualTo(actual.getCustomerName()))
            .satisfies(e -> assertThat(e.getDeliveryAddress()).as("check deliveryAddress").isEqualTo(actual.getDeliveryAddress()))
            .satisfies(e -> assertThat(e.getDeliveryLocation()).as("check deliveryLocation").isEqualTo(actual.getDeliveryLocation()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFoodOrderUpdatableRelationshipsEquals(FoodOrder expected, FoodOrder actual) {
        assertThat(expected)
            .as("Verify FoodOrder relationships")
            .satisfies(e -> assertThat(e.getRestaurant()).as("check restaurant").isEqualTo(actual.getRestaurant()))
            .satisfies(e -> assertThat(e.getDeliveryPartner()).as("check deliveryPartner").isEqualTo(actual.getDeliveryPartner()));
    }
}
